stages:
  - push_dev
  - push_test
  
push_dev:
  stage: push_dev
  only:
    - dev
  script:
    - ssh workverse-backend@$harshika "cd /home/workverse-backend/server/dev/spotboi-frontend/ && git fetch && git reset --hard origin/dev && docker stop spotboi-frontend || true && docker compose up -d --build"

push_test:
  stage: push_test
  only:
    - test
  script:
    - ssh workverse-backend@$harshika "cd /home/workverse-backend/server/test/spotboi-frontend/ && git fetch && git reset --hard rigin/test && docker stop spotboi-frontend || true && docker compose up -d --build"
